name: Deploy Rekognition Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        run: terraform init

      # Step 1: Bootstrap the Repository
      - name: Terraform Target ECR
        run: terraform apply -target=aws_ecr_repository.rekognition_repo -auto-approve

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 2: Push the AI Model
      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: group3-rekognition-repo
          IMAGE_TAG: latest
        run: |
          docker build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # Step 3: Complete Infrastructure
      - name: Terraform Apply Full
        run: terraform apply -auto-approve

      # Step 4: Inject API and Sync Frontend
      - name: Inject API URL and Deploy to S3
        run: |
          REAL_URL=$(terraform output -raw api_endpoint)
          sed -i "s|REPLACE_ME_API_URL|$REAL_URL|g" website/script.js
          BUCKET_NAME=$(terraform output -raw website_bucket_name)
          aws s3 sync ./website s3://$BUCKET_NAME --delete